### ISSUE TITLE
Get Codesonar up and running locally

### ISSUE THREAD

**Issue by kryptag** [Praqma/codesonar-plugin#15]
This issue is about getting the environment up and running and make it possible to analyse a project

1. Send mail to codesonar
2. get login
3. download codesonar
4. follow installation guide
5. request license
6. add license to local codesonar instance
7. Document the proces and make it reproducible

**Comment by MadsNielsen** [comment]
Added 7(th) item for you @kryptag ;)

**Comment by kryptag** [comment]
@MadsNielsen when you say reproducible, are we talking a script or a guide?

**Comment by buep** [comment]
use ansible playbooks :-)

**Comment by MadsNielsen** [comment]
@kryptag Let's start with a guide..... :) And if you're super adventourous...try ansible as suggest by @buep :P

**Comment by les-praqma** [comment]
Did we do some handover from Andrius? So we don't look unprofessional and ask GrammaTech for things they expect us to know already?

**Comment by MadsNielsen** [comment]
@les-praqma  The handover was mostly technical and about the code, the pipeline setup etc. I guess this lack of information is a failure on my part.  

But, before sending the mail, @kryptag need to get codesonar installed, that requires you to register and/or submit to a trial license, since they do not have a download link on their site. The license request needs to be generated once the hub is installed on the computer with a command line utility that comes with the hub. That is for a start...we might not need ask Paul right away.

**Comment by kryptag** [comment]
I have fixed everything when it comes to license, i just followed their guide and i got it up and running

**Comment by MadsNielsen** [comment]
@kryptag great :)
